PRODUCTS = [
 {'id':'p01','title':'Aero 轻量降噪耳机','category':'audio','price':'79.00','stock':18,'icon':'🎧','color':'lavender','tags':'耳机 headphone headphones noise cancelling 降噪 蓝牙 通勤 音乐'},
 {'id':'p02','title':'Nomad 旅行双肩包 24L','category':'travel','price':'59.00','stock':25,'icon':'🎒','color':'peach','tags':'背包 backpack bag 旅行 通勤 防水 电脑包'},
 {'id':'p03','title':'Orbit USB-C 65W 充电器','category':'tech','price':'35.00','stock':40,'icon':'🔌','color':'mint','tags':'充电器 charger USB-C 旅行 手机 笔记本 快充'},
 {'id':'p04','title':'Terra 不锈钢保温杯','category':'home','price':'24.00','stock':30,'icon':'🥤','color':'sand','tags':'保温杯 bottle 水杯 户外 环保 运动'},
 {'id':'p05','title':'Luma 阅读台灯','category':'home','price':'42.00','stock':12,'icon':'💡','color':'peach','tags':'台灯 lamp 阅读 桌面 家居 护眼'},
 {'id':'p06','title':'Pulse 运动智能手表','category':'tech','price':'89.00','stock':16,'icon':'⌚','color':'lavender','tags':'手表 watch smartwatch 运动 健康 户外 蓝牙'},
 {'id':'p07','title':'Cloud 真无线耳塞','category':'audio','price':'39.00','stock':32,'icon':'🎵','color':'mint','tags':'耳机 耳塞 earbuds headphones 音乐 蓝牙 运动'},
 {'id':'p08','title':'Voyager 行李收纳套装','category':'travel','price':'19.00','stock':28,'icon':'🧳','color':'sand','tags':'收纳 packing cubes travel 旅行 行李 箱包'},
 {'id':'p09','title':'Atlas 20英寸登机箱','category':'luggage','price':'129.00','stock':14,'icon':'🧳','color':'sand','tags':'行李箱 suitcase luggage 拉杆箱 登机箱 万向轮 硬壳 旅行'},
 {'id':'p10','title':'Metro 24英寸静音轮行李箱','category':'luggage','price':'169.00','stock':10,'icon':'🧳','color':'peach','tags':'行李箱 suitcase luggage 拉杆箱 托运行李箱 静音轮 防刮 旅行'},
 {'id':'p11','title':'Roam 28英寸扩容箱','category':'luggage','price':'199.00','stock':8,'icon':'🧳','color':'lavender','tags':'行李箱 suitcase luggage 拉杆箱 托运 扩容 大容量 旅行'},
 {'id':'p12','title':'Civic 轻量软壳旅行箱','category':'luggage','price':'99.00','stock':20,'icon':'🧳','color':'mint','tags':'行李箱 suitcase luggage 软箱 拉杆箱 轻量 防水 旅行'},
 {'id':'p13','title':'Echo Pro 混合降噪耳机','category':'audio','price':'149.00','stock':11,'icon':'🎧','color':'lavender','tags':'耳机 headphones noise cancelling 降噪 通勤 头戴 麦克风 蓝牙'},
 {'id':'p14','title':'Breeze 开放式运动耳机','category':'audio','price':'69.00','stock':23,'icon':'🎵','color':'peach','tags':'耳机 earbuds 运动 跑步 开放式 防汗 蓝牙 音乐'},
 {'id':'p15','title':'Trail 防水旅行腰包','category':'travel','price':'29.00','stock':31,'icon':'🎒','color':'mint','tags':'腰包 sling bag 旅行 防水 轻便 徒步 随身包'},
 {'id':'p16','title':'Link USB-C 多口扩展坞','category':'tech','price':'49.00','stock':17,'icon':'🔌','color':'sand','tags':'扩展坞 hub USB-C 笔记本 HDMI 办公 旅行'},
 {'id':'p17','title':'Field 折叠旅行收纳袋','category':'travel','price':'22.00','stock':35,'icon':'🧳','color':'peach','tags':'旅行袋 收纳 bag 折叠 行李 轻便 箱包'},
 {'id':'p18','title':'Halo 智能行李追踪器','category':'travel','price':'25.00','stock':26,'icon':'📍','color':'lavender','tags':'行李追踪器 tracker luggage 蓝牙 防丢 旅行 定位'},
 {'id':'p19','title':'Nora 轻薄办公本','category':'tech','price':'699.00','stock':9,'icon':'💻','color':'lavender','tags':'笔记本 laptop 办公 学习 轻薄 USB-C 旅行'},
 {'id':'p20','title':'Dock Mini 旅行充电宝','category':'tech','price':'39.00','stock':27,'icon':'🔋','color':'mint','tags':'充电宝 power bank USB-C 旅行 飞行 手机 快充'},
 {'id':'p21','title':'Moss 便携折叠雨伞','category':'travel','price':'18.00','stock':42,'icon':'☂️','color':'sand','tags':'雨伞 umbrella 防风 防水 旅行 通勤 便携'},
 {'id':'p22','title':'Cedar 旅行洗漱包','category':'travel','price':'26.00','stock':24,'icon':'🧴','color':'peach','tags':'洗漱包 toiletry bag 旅行 收纳 防水 化妆包'},
 {'id':'p23','title':'Aster 颈挂式运动耳机','category':'audio','price':'45.00','stock':19,'icon':'🎧','color':'mint','tags':'耳机 headphones 运动 跑步 颈挂 防汗 蓝牙'},
 {'id':'p24','title':'Sonic Studio 监听耳机','category':'audio','price':'119.00','stock':7,'icon':'🎧','color':'sand','tags':'耳机 headphones 监听 音乐 有线 录音棚 音质'},
 {'id':'p25','title':'Kite 旅行相机包','category':'travel','price':'76.00','stock':13,'icon':'📷','color':'lavender','tags':'相机包 camera bag 旅行 防震 摄影 防水'},
 {'id':'p26','title':'Ridge 28英寸铝框行李箱','category':'luggage','price':'329.00','stock':6,'icon':'🧳','color':'sand','tags':'行李箱 suitcase luggage 铝框 拉杆箱 托运 防撞 大容量'},
 {'id':'p27','title':'Flex 20英寸前开盖登机箱','category':'luggage','price':'149.00','stock':15,'icon':'🧳','color':'peach','tags':'行李箱 suitcase luggage 登机箱 前开盖 电脑隔层 万向轮'},
 {'id':'p28','title':'Lumen 护眼显示器挂灯','category':'home','price':'58.00','stock':10,'icon':'💡','color':'mint','tags':'显示器挂灯 lamp 护眼 桌面 阅读 办公'},
 {'id':'p29','title':'Terra 便携咖啡杯','category':'home','price':'28.00','stock':33,'icon':'☕','color':'peach','tags':'咖啡杯 bottle 保温杯 防漏 通勤 户外 环保'},
 {'id':'p30','title':'Nest 智能桌面音箱','category':'home','price':'69.00','stock':18,'icon':'🔊','color':'lavender','tags':'音箱 speaker 蓝牙 家居 音乐 智能'},
]

DESCRIPTIONS = {
 'p01':'适合通勤和长途旅行的轻量头戴式降噪耳机，支持蓝牙连接，佩戴舒适。',
 'p02':'24L 防水旅行双肩包，带电脑隔层和行李箱固定带，适合通勤与短途出行。',
 'p03':'65W USB-C 氮化镓充电器，可同时为笔记本和手机充电，体积小巧适合旅行。',
 'p04':'双层不锈钢保温杯，适合办公室、户外和运动场景，杯盖防漏。',
 'p05':'可调色温阅读台灯，光线柔和，适合桌面阅读、学习和夜间办公。',
 'p06':'支持运动记录和健康监测的智能手表，适合跑步、户外和日常提醒。',
 'p07':'价格友好的真无线耳塞，体积小、连接方便，适合运动和通勤听歌。',
 'p08':'多尺寸旅行收纳袋套装，用于整理衣物、鞋子和配件，不是行李箱本体。',
 'p09':'20英寸硬壳登机箱，带万向轮和密码锁，适合短途出差和登机旅行。',
 'p10':'24英寸静音轮托运行李箱，外壳耐刮，容量适合一周左右的旅行。',
 'p11':'28英寸大容量扩容行李箱，适合长途旅行和托运，内部有分区收纳。',
 'p12':'轻量软壳旅行箱，带外部口袋和防水面料，适合需要快速取物的出行者。',
 'p13':'混合式主动降噪耳机，适合通勤、飞机和办公室，带通话麦克风。',
 'p14':'开放式运动耳机，佩戴时能听到环境声音，适合跑步和户外运动。',
 'p15':'轻便防水旅行腰包，可放手机、护照和小物，适合徒步和城市旅行。',
 'p16':'USB-C 多口扩展坞，提供 HDMI 和数据接口，适合办公桌面与出差使用。',
 'p17':'可折叠旅行收纳袋，收纳空间大且便于放进行李箱，适合回程装纪念品。',
 'p18':'蓝牙行李追踪器，可放进行李或背包，帮助旅行者寻找遗失物品。',
 'p19':'轻薄办公本，适合文档、网页和学习任务，支持 USB-C 充电和移动办公。',
 'p20':'适合飞行和日常出行的便携充电宝，支持 USB-C 快充，容量适中。',
 'p21':'防风折叠雨伞，收纳体积小，适合放在通勤包和旅行背包中。',
 'p22':'防水旅行洗漱包，内部多个分区，适合收纳牙刷、护肤品和小瓶液体。',
 'p23':'颈挂式运动耳机，运动时不易掉落，支持防汗和蓝牙连接。',
 'p24':'有线监听耳机，强调声音细节，适合音乐制作、录音和认真听歌。',
 'p25':'带防震隔层的旅行相机包，适合携带相机、镜头和备用电池。',
 'p26':'铝框硬壳行李箱，防撞结构和大容量设计，适合长途托运。',
 'p27':'前开盖登机箱，可快速取出电脑和文件，适合商务出差。',
 'p28':'显示器挂灯，减少桌面阴影，适合夜间办公、阅读和学习。',
 'p29':'防漏便携咖啡杯，适合通勤携带热饮，也可作为日常保温杯使用。',
 'p30':'小型智能桌面音箱，支持蓝牙播放，适合卧室、书桌和小空间音乐播放。',
}
async def seed(db):
    async with db.transaction() as u:
        for p in PRODUCTS:
            existing=await u.get('products',p['id'],'*') or {}
            row={**p,**existing,'description':DESCRIPTIONS[p['id']]}
            await u.put('products',p['id'],'*',row)
