from typing import Protocol, Any, AsyncContextManager
from app.domain.models import ShoppingContext

class UnitOfWork(Protocol):
    async def get(self, kind: str, id: str, owner: str) -> dict | None: ...
    async def put(self, kind: str, id: str, owner: str, data: dict) -> None: ...
    async def list(self, kind: str, owner: str) -> list[dict]: ...
    async def event(self, ctx: ShoppingContext, type: str, data: dict) -> None: ...

class Repository(Protocol):
    def transaction(self) -> AsyncContextManager[UnitOfWork]: ...

class SearchPort(Protocol):
    async def search(self, query: str, limit: int = 6, category: str | None = None, max_price: float | None = None) -> dict: ...
    async def knowledge(self, query: str) -> dict: ...
    async def web(self, query: str) -> dict: ...
    async def web_to_knowledge(self, query: str) -> dict: ...

class AgentRuntime(Protocol):
    async def run(self, ctx: ShoppingContext, text: str, state: dict | None) -> tuple[str, dict]: ...
